version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ../..:/workspaces:cached
      - ../dev/configuration.py:/workspaces/luxbuster/luxcontrol/luxcontrol/luxcontrol/configuration.py
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_data:
